services:  
  db:
    image: postgis/postgis:17-3.5
    container_name: moi_db
    environment:
       POSTGRES_HOST_AUTH_METHOD: trust
       POSTGRES_PASSWORD: postgres
       POSTGRES_USER: postgres
       POSTGRES_DB: moi

  adminer:
    command: php -S 0.0.0.0:8080 -t /var/www/html
    image: adminer:4.8.1
    depends_on: 
      - db
    ports:
      - 8080:8080
    container_name: moi_adminer
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    depends_on:
      - db
    container_name: moi_web
