# Generated by Django 6.0.7 on 2026-08-01 16:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import stdimage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, help_text='Do not edit... auto-generated by the system', null=True)),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='records', variations={'large': (1280, 1024), 'thumbnail': (480, 480)})),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('old_id', models.IntegerField(blank=True, db_index=True, help_text='Only used for the migration between old and new structure', null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(blank=True, choices=[('academic', 'Academic'), ('reports', 'Reports'), ('data', 'Data'), ('multimedia', 'Multimedia'), ('other', 'Other')], max_length=20, null=True)),
                ('bibtex_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ris_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Should only be set for permissions, and should only be modified by the programming team', max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_permission', models.BooleanField(default=False, help_text='Mark if this relationship is about giving people permissions in the system')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.record')),
                ('language', models.CharField(blank=True, choices=[('EN', 'English'), ('ES', 'Spanish'), ('CH', 'Chinese'), ('FR', 'French'), ('GE', 'German'), ('NL', 'Dutch'), ('PT', 'Portuguese'), ('CT', 'Catalan'), ('FI', 'Finnish'), ('DN', 'Danish'), ('NO', 'Norwegian'), ('OT', 'Other')], default='EN', max_length=2, null=True)),
                ('title_original_language', models.CharField(blank=True, max_length=255, null=True)),
                ('author_list', models.TextField(blank=True, null=True)),
                ('author_citation', models.TextField(blank=True, null=True)),
                ('bibtex_citation', models.TextField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('abstract_original_language', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='library')),
                ('url', models.CharField(blank=True, max_length=2048, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('open_access', models.BooleanField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('deleted', 'Deleted')], db_index=True, help_text='Old field, do not use', max_length=8, null=True)),
                ('is_part_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.libraryitem')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.license')),
                ('saved_by_users', models.ManyToManyField(blank=True, related_name='saved_library_items', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.libraryitemtype')),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
            bases=('main.record',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.record')),
                ('date', models.DateField()),
                ('slug', models.SlugField(max_length=255)),
                ('include_in_timeline', models.BooleanField(default=False)),
                ('article_type', models.CharField(choices=[('news', 'News'), ('blog', 'Blog')], default='news', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-date', '-id'],
            },
            bases=('main.record',),
        ),
        migrations.CreateModel(
            name='OptamosProject',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.record')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('goal', models.CharField(blank=True, max_length=255)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
            ],
            bases=('main.record',),
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.record')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('email_public', models.BooleanField(default=False)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('google_scholar', models.CharField(blank=True, max_length=255, null=True)),
                ('orcid', models.CharField(blank=True, max_length=255, null=True)),
                ('researchgate', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('research_interests', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('deceased', 'Deceased'), ('inactive', 'Inactive'), ('pending', 'Pending Review')], default='active', max_length=8)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
            bases=('main.record',),
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.record')),
                ('type', models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown'), ('markdown_html', 'Markdown and HTML')], default='markdown', max_length=13)),
                ('slug', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('main.record',),
        ),
        migrations.CreateModel(
            name='ZoteroCollection',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.record')),
                ('api', models.CharField(max_length=255)),
                ('zotero_id', models.CharField(max_length=255)),
            ],
            bases=('main.record',),
        ),
        migrations.CreateModel(
            name='OptamosCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(db_index=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.optamoscriteria')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='main.optamosproject')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RecordRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('record_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_list', to='main.record')),
                ('record_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_list', to='main.record')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.relationship')),
            ],
            options={
                'verbose_name': 'relationship manager',
                'verbose_name_plural': 'relationship manager',
                'unique_together': {('record_parent', 'relationship', 'record_child')},
            },
        ),
        migrations.AddField(
            model_name='record',
            name='child_of',
            field=models.ManyToManyField(related_name='parent_of_child', through='main.RecordRelationship', through_fields=('record_child', 'record_parent'), to='main.record'),
        ),
        migrations.AddField(
            model_name='record',
            name='parent_to',
            field=models.ManyToManyField(related_name='child_of_parent', through='main.RecordRelationship', through_fields=('record_parent', 'record_child'), to='main.record'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, help_text='Do not edit... auto-generated by the system', null=True)),
                ('hidden', models.BooleanField(db_index=True, default=False, help_text='Mark if tag is superseded/not yet approved/deactivated')),
                ('include_in_glossary', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('icon', models.CharField(blank=True, help_text='Only include the icon name, not fa- classes --- see https://fontawesome.com/icons?d=gallery', max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.record')),
                ('parent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.record')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='documents')),
                ('attached_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.record')),
            ],
            bases=('main.record',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('libraryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.libraryitem')),
                ('position', models.PositiveSmallIntegerField(blank=True, db_index=True, default=1, null=True)),
            ],
            bases=('main.libraryitem',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('libraryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.libraryitem')),
                ('embed_code', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('video_site', models.CharField(choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo'), ('ted', 'TED'), ('other', 'Other')], max_length=14)),
            ],
            bases=('main.libraryitem',),
        ),
        migrations.CreateModel(
            name='OptamosTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_list', to='main.optamosproject')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OptamosAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='main.optamosproject')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='record',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed', to='main.people'),
        ),
        migrations.CreateModel(
            name='ReferenceSpace',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.record')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.libraryitem')),
            ],
            options={
                'db_table': 'stafdb_referencespace',
                'ordering': ['name'],
            },
            bases=('main.record',),
        ),
        migrations.AddField(
            model_name='record',
            name='spaces',
            field=models.ManyToManyField(blank=True, to='main.referencespace'),
        ),
        migrations.CreateModel(
            name='ActivatedSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=255)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activated', to='main.referencespace')),
            ],
            options={
                'ordering': ['space__name'],
            },
        ),
        migrations.CreateModel(
            name='ZoteroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('library_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.libraryitem')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.zoterocollection')),
            ],
        ),
        migrations.CreateModel(
            name='OptamosAlternativeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('alternative1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting1', to='main.optamosalternative')),
                ('alternative2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting2', to='main.optamosalternative')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_pairs', to='main.optamoscriteria')),
            ],
            options={
                'unique_together': {('criteria', 'alternative1', 'alternative2', 'user')},
            },
        ),
        migrations.CreateModel(
            name='OptamosCriteriaValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('criteria1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting1', to='main.optamoscriteria')),
                ('criteria2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting2', to='main.optamoscriteria')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('criteria1', 'criteria2', 'user')},
            },
        ),
        migrations.CreateModel(
            name='OptamosUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('admin', 'Administrator'), ('regular', 'Regular user')], default='regular', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.optamosproject')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
