# Generated by Django 6.0.7 on 2026-08-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivatedSpace',
            new_name='Island',
        ),
    ]
