# Generated by Django 6.0.7 on 2026-08-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_activatedspace_island'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='region',
            field=models.CharField(choices=[('pacific', 'Pacific Ocean'), ('indian', 'Indian Ocean'), ('caribbean', 'Caribbean'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
