# Generated by Django 6.0.7 on 2026-08-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_island_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='island',
            name='region',
        ),
    ]
