# Generated by Django 6.0.7 on 2026-08-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_island_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='region',
            field=models.IntegerField(choices=[(1, 'Pacific Ocean'), (2, 'Caribbean'), (3, 'Indian Ocean'), (4, 'Other')], db_index=True, null=True),
        ),
    ]
