# Generated by Django 6.0.7 on 2026-08-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_island_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencespace',
            name='source',
        ),
        migrations.AddField(
            model_name='referencespace',
            name='region',
            field=models.IntegerField(choices=[(1, 'Pacific Ocean'), (2, 'Caribbean'), (3, 'Indian Ocean'), (4, 'Other')], db_index=True, null=True),
        ),
    ]
