# Generated by Django 6.0.7 on 2026-08-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_referencespace_source_referencespace_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencespace',
            name='slug',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
