# Generated by Django 6.0.7 on 2026-08-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_referencespace_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Island',
        ),
    ]
