# Generated by Django 6.0.7 on 2026-08-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_island'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferenceSpace',
            new_name='Island',
        ),
    ]
