# Generated by Django 6.0.7 on 2026-08-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_referencespace_island'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='section',
            field=models.CharField(choices=[('about', 'About'), ('other', 'Other')], default='other', max_length=13),
        ),
    ]
