# Generated by Django 6.0.7 on 2026-08-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_webpage_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='section',
            field=models.CharField(choices=[('about', 'About'), ('research', 'Research'), ('other', 'Other')], default='other', max_length=13),
        ),
    ]
