# Generated by Django 6.0.7 on 2026-08-02 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_webpage_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProject',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.record')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('target_finish_date', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='ongoing', max_length=20)),
                ('type', models.CharField(choices=[('thesis', 'Thesis project'), ('research', 'Research project')], default='research', max_length=20)),
                ('part_of_project', models.PositiveSmallIntegerField(db_index=True)),
            ],
            bases=('main.record',),
        ),
    ]
