# Generated by Django 6.0.7 on 2026-08-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_publicproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicproject',
            old_name='part_of_project',
            new_name='part_of_project_id',
        ),
    ]
