# Generated by Django 6.0.7 on 2026-08-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_part_of_project_publicproject_part_of_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicproject',
            old_name='type',
            new_name='project_type',
        ),
        migrations.RemoveField(
            model_name='publicproject',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='publicproject',
            name='part_of_project_id',
        ),
    ]
