# Generated by Django 6.0.7 on 2026-08-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_type_publicproject_project_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='island',
            old_name='region',
            new_name='old_region',
        ),
    ]
