# Generated by Django 6.0.7 on 2026-08-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_region_island_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='island',
            name='old_region',
        ),
    ]
