# Generated by Django 6.0.7 on 2026-08-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_island_old_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='article_type',
        ),
    ]
