# Generated by Django 6.0.7 on 2026-08-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_news_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.record')),
                ('type', models.CharField(blank=True, choices=[('conference', 'Conference'), ('hackathon', 'Hackathon'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('summerschool', 'Summer School'), ('other', 'Other'), ('training_outreach', 'Training and Outreach')], max_length=20, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
            bases=('main.record',),
        ),
    ]
