# Generated by Django 6.0.7 on 2026-08-04 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='photo_island',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depicted_region', to='main.island'),
        ),
        migrations.AlterField(
            model_name='island',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='islands', to='main.region'),
        ),
    ]
