# Generated by Django 6.0.7 on 2026-08-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_region_photo_island_alter_island_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='section',
            field=models.CharField(choices=[('about', 'About'), ('research', 'Research'), ('resources', 'Resources'), ('other', 'Other')], default='other', max_length=13),
        ),
    ]
