# Generated by Django 6.0.7 on 2026-08-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_webpage_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_site',
        ),
    ]
