# Generated by Django 6.0.7 on 2026-08-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_event_type_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='email_public',
        ),
        migrations.RemoveField(
            model_name='people',
            name='status',
        ),
        migrations.AddField(
            model_name='people',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
