# Generated by Django 6.0.8 on 2026-08-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_people_email_public_remove_people_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_highlight',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
