# Generated by Django 6.0.8 on 2026-08-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_video_is_highlight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicProject',
            new_name='Research',
        ),
    ]
