# Generated by Django 6.0.8 on 2026-08-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_publicproject_research'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='status',
        ),
    ]
