# Generated by Django 6.0.8 on 2026-08-07 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_research_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.record')),
            ],
            bases=('main.record',),
        ),
        migrations.RemoveField(
            model_name='libraryitem',
            name='saved_by_users',
        ),
        migrations.RemoveField(
            model_name='libraryitem',
            name='status',
        ),
    ]
