# Generated by Django 6.0.8 on 2026-08-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_publisher_remove_libraryitem_saved_by_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.publisher'),
        ),
    ]
