# Generated by Django 6.0.8 on 2026-08-07 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_libraryitem_published_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryitem',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='main.publisher'),
        ),
    ]
