# Generated by Django 6.0.8 on 2026-08-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_libraryitem_published_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='people',
            name='twitter',
        ),
    ]
