# Generated by Django 6.0.8 on 2026-08-27 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_people_linkedin_remove_people_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='landscape_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='islands_landscape', to='main.region'),
        ),
        migrations.AddField(
            model_name='island',
            name='main_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='islands_main', to='main.photo'),
        ),
    ]
