# Generated by Django 6.0.8 on 2026-08-27 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_island_landscape_photo_island_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='landscape_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='islands_landscape', to='main.photo'),
        ),
    ]
