# Generated by Django 6.0.8 on 2026-08-27 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_island_landscape_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='island',
            old_name='main_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='island',
            old_name='landscape_photo',
            new_name='photo_bg',
        ),
    ]
