# Generated by Django 6.0.8 on 2026-09-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_rename_main_photo_island_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged', to='main.tag'),
        ),
    ]
