# Generated by Django 6.0.8 on 2026-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_region_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='a'),
            preserve_default=False,
        ),
    ]
