# Generated by Django 6.0.8 on 2026-09-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_zoteroitem_processing_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='controlpanel_access',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='island_access',
            field=models.ManyToManyField(blank=True, to='main.island'),
        ),
    ]
