# Generated by Django 6.0.8 on 2026-09-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_people_controlpanel_access_people_island_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='access_type',
            field=models.CharField(choices=[('full', 'Full access'), ('islands_only', 'Islands-only'), ('controlpanel_only', 'Controlpanel-only')], max_length=20, null=True),
        ),
    ]
