# Generated by Django 6.0.8 on 2026-09-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_people_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='access_type',
            field=models.CharField(choices=[('full', 'Full Access'), ('islands_only', 'Selected island(s)'), ('controlpanel_only', 'Selected section(s)')], max_length=20, null=True),
        ),
    ]
