# Generated by Django 6.0.8 on 2026-09-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_people_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='map_zoom',
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
