# Generated by Django 4.1.2 on 2025-04-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_libraryitem_saved_by_users'),
        ('core', '0108_remove_libraryitem_data_type_delete_datasettype'),
    ]

    operations = [
    ]
