# Generated by Django 4.1.2 on 2025-04-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_delete_cityloopshandbookpage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='SocialMediaPlatform',
        ),
    ]
