# Generated by Django 4.1.2 on 2025-04-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_delete_socialmedia_delete_socialmediaplatform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialDemand',
        ),
    ]
