# Generated by Django 4.1.2 on 2025-04-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_delete_materialdemand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.libraryitemtype'),
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
