# Generated by Django 4.2 on 2025-04-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_delete_materialdemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('news', 'News'), ('blog', 'Blog')], default='news', max_length=10),
        ),
    ]
