# Generated by Django 4.2 on 2025-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_alter_libraryitem_type_delete_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article_type',
            field=models.CharField(choices=[('news', 'News'), ('blog', 'Blog')], default='news', max_length=10),
        ),
    ]
