# Generated by Django 6.0 on 2025-12-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_news_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptamosProject',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.record')),
            ],
            bases=('core.record',),
        ),
        migrations.AlterField(
            model_name='record',
            name='child_of',
            field=models.ManyToManyField(related_name='parent_of_child', through='core.RecordRelationship', through_fields=('record_child', 'record_parent'), to='core.record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='parent_to',
            field=models.ManyToManyField(related_name='child_of_parent', through='core.RecordRelationship', through_fields=('record_parent', 'record_child'), to='core.record'),
        ),
    ]
