# Generated by Django 6.0 on 2025-12-25 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_optamosproject_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optamosproject',
            name='user',
        ),
        migrations.AddField(
            model_name='optamosproject',
            name='user',
            field=models.ManyToManyField(related_name='optamos', to=settings.AUTH_USER_MODEL),
        ),
    ]
