# Generated by Django 6.0 on 2025-12-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_remove_optamosproject_user_optamosproject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='optamosproject',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='optamosproject',
            name='goal',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
