# Generated by Django 4.2.26 on 2025-12-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_optamosproject_date_updated_optamosproject_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptamosOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.optamosproject')),
            ],
        ),
        migrations.CreateModel(
            name='OptamosCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='core.optamosproject')),
            ],
        ),
    ]
