# Generated by Django 4.2.26 on 2025-12-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_optamosoption_optamoscriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptamosOptionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.optamoscriteria')),
                ('option1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting1', to='core.optamosoption')),
                ('option2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting2', to='core.optamosoption')),
            ],
        ),
    ]
