# Generated by Django 4.2.26 on 2025-12-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_optamosoptionvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optamosoptionvalue',
            name='value',
            field=models.SmallIntegerField(),
        ),
    ]
