# Generated by Django 4.2.26 on 2025-12-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_alter_optamosoptionvalue_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optamoscriteria',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='optamosoption',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='optamosoptionvalue',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_pairs', to='core.optamoscriteria'),
        ),
    ]
