# Generated by Django 4.2.26 on 2025-12-29 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_alter_optamoscriteria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptamosCriteriaValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('criteria1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting1', to='core.optamoscriteria')),
                ('criteria2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting2', to='core.optamoscriteria')),
            ],
        ),
    ]
