# Generated by Django 4.2.26 on 2026-03-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_optamoscriteriavalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptamosTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_list', to='core.optamosproject')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
