# Generated by Django 4.2.26 on 2026-03-21 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_optamostag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptamosOption',
            new_name='OptamosAlternative',
        ),
        migrations.RenameModel(
            old_name='OptamosOptionValue',
            new_name='OptamosAlternativeValue',
        ),
    ]
