# Generated by Django 4.2.26 on 2026-03-21 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_rename_optamosoption_optamosalternative_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optamosalternativevalue',
            old_name='option1',
            new_name='alternative1',
        ),
        migrations.RenameField(
            model_name='optamosalternativevalue',
            old_name='option2',
            new_name='alternative2',
        ),
        migrations.AlterField(
            model_name='optamosalternative',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='core.optamosproject'),
        ),
        migrations.AlterField(
            model_name='optamosalternativevalue',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_pairs', to='core.optamoscriteria'),
        ),
    ]
