# Generated by Django 6.0.3 on 2026-03-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_rename_option1_optamosalternativevalue_alternative1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optamoscriteria',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
