# Generated by Django 6.0.3 on 2026-03-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_optamosuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optamosproject',
            name='user',
        ),
        migrations.AlterField(
            model_name='optamosuser',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.optamosproject'),
        ),
    ]
