# Generated by Django 6.0.3 on 2026-03-26 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_remove_optamosproject_user_alter_optamosuser_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optamosuser',
            unique_together={('project', 'user')},
        ),
    ]
