# Generated by Django 6.0.3 on 2026-03-26 18:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_alter_optamosalternativevalue_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optamosalternativevalue',
            unique_together={('alternative1', 'alternative2', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='optamoscriteriavalue',
            unique_together={('criteria1', 'criteria2', 'user')},
        ),
    ]
