# Generated by Django 6.0.3 on 2026-03-26 20:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_alter_optamosalternativevalue_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optamosalternativevalue',
            unique_together={('criteria', 'alternative1', 'alternative2', 'user')},
        ),
    ]
