# Generated by Django 6.0.3 on 2026-04-02 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_alter_optamosalternativevalue_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='optamosalternativevalue',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='optamoscriteriavalue',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='optamoscriteriavalue',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
