# Generated by Django 6.0.3 on 2026-04-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_alter_optamosalternativevalue_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optamosalternativevalue',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='optamoscriteriavalue',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
