# Generated by Django 6.0.3 on 2026-04-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_alter_optamosalternativevalue_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optamoscriteria',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='optamoscriteria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.optamoscriteria'),
        ),
        migrations.AddField(
            model_name='optamoscriteria',
            name='position',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
